spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop_review
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # >> 16. 배치사이즈 설정 ( 100 의미는 땡겨오는 in 쿼리 개수를 100개로 제한 )
        default_batch_fetch_size: 100
#        show_sql: true
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
